use notan::prelude::*;

pub fn letter_to_option(key: KeyCode, shift: bool) -> i32 {
    if shift {
        match key {
            KeyCode::A => 26,
            KeyCode::B => 27,
            KeyCode::C => 28,
            KeyCode::D => 29,
            KeyCode::E => 30,
            KeyCode::F => 31,
            KeyCode::G => 32,
            KeyCode::H => 33,
            KeyCode::I => 34,
            KeyCode::J => 35,
            KeyCode::K => 36,
            KeyCode::L => 37,
            KeyCode::M => 38,
            KeyCode::N => 39,
            KeyCode::O => 40,
            KeyCode::P => 41,
            KeyCode::Q => 42,
            KeyCode::R => 43,
            KeyCode::S => 44,
            KeyCode::T => 45,
            KeyCode::U => 46,
            KeyCode::V => 47,
            KeyCode::W => 48,
            KeyCode::X => 49,
            KeyCode::Y => 50,
            KeyCode::Z => 51,
            _ => -1,
        }
    } else {
        match key {
            KeyCode::A => 0,
            KeyCode::B => 1,
            KeyCode::C => 2,
            KeyCode::D => 3,
            KeyCode::E => 4,
            KeyCode::F => 5,
            KeyCode::G => 6,
            KeyCode::H => 7,
            KeyCode::I => 8,
            KeyCode::J => 9,
            KeyCode::K => 10,
            KeyCode::L => 11,
            KeyCode::M => 12,
            KeyCode::N => 13,
            KeyCode::O => 14,
            KeyCode::P => 15,
            KeyCode::Q => 16,
            KeyCode::R => 17,
            KeyCode::S => 18,
            KeyCode::T => 19,
            KeyCode::U => 20,
            KeyCode::V => 21,
            KeyCode::W => 22,
            KeyCode::X => 23,
            KeyCode::Y => 24,
            KeyCode::Z => 25,
            _ => -1,
        }
    }
}
