pub const DEFAULT_VIEWSHED_STANDARD: i32 = 6; //       Standard viewshed radius for almost all entities.
pub const CARRY_CAPACITY_PER_STRENGTH: i32 = 5; //      How much weight can be carried per point of strength.
pub const NORMAL_SPEED: i32 = 12; //                    Normal speed for almost all entities.
pub const SPEED_MOD_BURDENED: f32 = 0.75;
pub const SPEED_MOD_STRAINED: f32 = 0.5;
pub const SPEED_MOD_OVERLOADED: f32 = 0.25;
pub const SPEED_MOD_OVERMAP_TRAVEL: f32 = 0.33;
pub const TURN_COST_MULTIPLIER: i32 = 4; //             How many ticks for NORMAL_SPEED to get a turn.
pub const ATTR_BONUS_0: i32 = 10; //                    At this value, the attribute bonus is 0.
pub const ATTR_NEEDED_PER_POINT: i32 = 2; //            How many points +- ATTR_BONUS_0 are needed per +- 1 bonus.
pub const STANDARD_HIT_DIE: i32 = 8; //                 Standard hit die used for rolling HP.
pub const STANDARD_HIT_DIE_0: i32 = 4; //               Standard hit die used for rolling HP for level 0.
pub const STANDARD_MANA_DIE: i32 = 4; //                Standard mana die used for rolling mana.
pub const MINIMUM_MANA: i32 = 0; //                     The minimum mana a monster can have.
pub const MINIMUM_MANA_PLAYER: i32 = 1; //              The minimum mana a player can have.
pub const STANDARD_BAC: i32 = 10; //                    Standard BASE AC.
